import { StyleSheet } from 'react-native';

export const createStyles = (isDarkMode) => StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: isDarkMode ? '#000000' : '#ffffff',
    fontFamily: 'Courier New',
  },
  header: {
    fontSize: 28,
    fontWeight: '300',
    marginBottom: 32,
    color: isDarkMode ? '#ffffff' : '#000000',
    textAlign: 'center',
    fontFamily: 'Courier New',
    letterSpacing: 2,
    textTransform: 'lowercase',
    borderBottomWidth: 1,
    borderBottomColor: isDarkMode ? '#333333' : '#cccccc',
    paddingBottom: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: isDarkMode ? '#444444' : '#bbbbbb',
    backgroundColor: isDarkMode ? '#111111' : '#f8f8f8',
    borderRadius: 0,
    padding: 16,
    marginBottom: 16,
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    fontSize: 16,
    textTransform: 'lowercase',
    letterSpacing: 1,
  },
  total: {
    fontSize: 20,
    fontWeight: '300',
    marginTop: 32,
    marginBottom: 24,
    color: isDarkMode ? '#ffffff' : '#000000',
    textAlign: 'center',
    fontFamily: 'Courier New',
    letterSpacing: 1.5,
    textTransform: 'lowercase',
    backgroundColor: isDarkMode ? '#111111' : '#f0f0f0',
    padding: 16,
    borderWidth: 1,
    borderColor: isDarkMode ? '#333333' : '#cccccc',
  },
  mealItem: {
    fontSize: 16,
    marginBottom: 12,
    color: isDarkMode ? '#cccccc' : '#333333',
    fontFamily: 'Courier New',
    letterSpacing: 1,
    textTransform: 'lowercase',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: isDarkMode ? '#0a0a0a' : '#f5f5f5',
    borderLeftWidth: 2,
    borderLeftColor: isDarkMode ? '#333333' : '#cccccc',
    marginHorizontal: 8,
  },
  toggleButton: {
    position: 'absolute',
    top: 50,
    right: 24,
    padding: 12,
    backgroundColor: isDarkMode ? '#333333' : '#dddddd',
    borderWidth: 1,
    borderColor: isDarkMode ? '#555555' : '#aaaaaa',
  },
  toggleButtonText: {
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    fontSize: 12,
    textTransform: 'lowercase',
    letterSpacing: 1,
  },
});
