import { StyleSheet } from 'react-native';

export const createStyles = (isDarkMode) => StyleSheet.create({
  container: {
    flex: 1,
    padding: 32,
    backgroundColor: isDarkMode ? '#000000' : '#ffffff',
    fontFamily: 'Courier New',
  },  header: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 8,
    color: isDarkMode ? '#ffffff' : '#000000',
    textAlign: 'center',
    fontFamily: 'Courier New',
    letterSpacing: 2,
    textTransform: 'lowercase',
  },
  subtitle: {
    fontSize: 14,
    fontWeight: '300',
    marginBottom: 24,
    color: isDarkMode ? '#888888' : '#666666',
    textAlign: 'center',
    fontFamily: 'Courier New',
    letterSpacing: 0.5,
    fontStyle: 'italic',
  },input: {
    borderWidth: 1,
    borderColor: isDarkMode ? '#444444' : '#bbbbbb',
    backgroundColor: isDarkMode ? '#111111' : '#f8f8f8',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    marginHorizontal: 24,
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    fontSize: 16,
    textTransform: 'lowercase',
    letterSpacing: 1,
  },  goalInput: {
    borderWidth: 1,
    borderColor: isDarkMode ? '#444444' : '#bbbbbb',
    backgroundColor: isDarkMode ? '#111111' : '#f8f8f8',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    marginTop: 40,
    marginHorizontal: 24,
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    fontSize: 16,
    textTransform: 'lowercase',
    letterSpacing: 1,
    textAlign: 'center',
  },  total: {
    fontSize: 20,
    fontWeight: '300',
    marginTop: 24,
    marginBottom: 16,
    marginHorizontal: 24,
    color: isDarkMode ? '#ffffff' : '#000000',
    textAlign: 'center',
    fontFamily: 'Courier New',
    letterSpacing: 1.5,
    textTransform: 'lowercase',
    backgroundColor: isDarkMode ? '#111111' : '#f0f0f0',
    padding: 20,
    borderWidth: 1,
    borderColor: isDarkMode ? '#333333' : '#cccccc',
    borderRadius: 12,
  },  mealItem: {
    fontSize: 16,
    marginBottom: 16,
    color: isDarkMode ? '#cccccc' : '#333333',
    fontFamily: 'Courier New',
    letterSpacing: 1,
    textTransform: 'lowercase',
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: isDarkMode ? '#0a0a0a' : '#f5f5f5',
    borderWidth: 1,
    borderColor: isDarkMode ? '#333333' : '#cccccc',
    marginHorizontal: 16,
    borderRadius: 10,
  },  toggleButton: {
    alignSelf: 'center',
    width: 60,
    height: 30,
    borderRadius: 15,
    backgroundColor: isDarkMode ? '#333333' : '#dddddd',
    borderWidth: 2,
    borderColor: isDarkMode ? '#555555' : '#aaaaaa',
    justifyContent: 'center',
    alignItems: isDarkMode ? 'flex-end' : 'flex-start',
    paddingHorizontal: 3,
    marginBottom: 40,
  },
  toggleButtonInner: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: isDarkMode ? '#ffffff' : '#000000',
  },  addButton: {
    backgroundColor: isDarkMode ? '#222222' : '#eeeeee',
    borderWidth: 1,
    borderColor: isDarkMode ? '#444444' : '#cccccc',
    paddingVertical: 20,
    paddingHorizontal: 32,
    marginTop: 16,
    marginHorizontal: 24,
    borderRadius: 12,
  },
  addButtonText: {
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    fontSize: 16,
    textTransform: 'lowercase',
    letterSpacing: 1,
    textAlign: 'center',
  },
  
  // Navigation styles
  navButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: isDarkMode ? '#222222' : '#eeeeee',
    borderWidth: 1,
    borderColor: isDarkMode ? '#444444' : '#cccccc',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    zIndex: 1000,
  },
  navButtonText: {
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    fontSize: 12,
    textTransform: 'lowercase',
    letterSpacing: 1,
  },
  
  // Analytics styles
  chartContainer: {
    marginHorizontal: 16,
    marginVertical: 20,
    backgroundColor: isDarkMode ? '#111111' : '#f8f8f8',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: isDarkMode ? '#333333' : '#cccccc',
  },
  chartTitle: {
    fontSize: 18,
    fontWeight: '300',
    marginBottom: 16,
    color: isDarkMode ? '#ffffff' : '#000000',
    textAlign: 'center',
    fontFamily: 'Courier New',
    letterSpacing: 1.5,
    textTransform: 'lowercase',
  },
  barContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 120,
    paddingHorizontal: 10,
  },
  barItem: {
    alignItems: 'center',
    marginHorizontal: 8,
    width: 40,
  },
  bar: {
    width: 20,
    backgroundColor: isDarkMode ? '#444444' : '#888888',
    borderRadius: 2,
    minHeight: 5,
  },
  barLabel: {
    fontSize: 10,
    color: isDarkMode ? '#cccccc' : '#666666',
    fontFamily: 'Courier New',
    marginTop: 4,
    textTransform: 'lowercase',
  },
  barValue: {
    fontSize: 12,
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    marginTop: 2,
  },
  lineContainer: {
    height: 120,
    position: 'relative',
  },
  lineChart: {
    height: 100,
    position: 'relative',
  },
  linePoint: {
    position: 'absolute',
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: isDarkMode ? '#ffffff' : '#000000',
  },
  lineSegment: {
    position: 'absolute',
    height: 1,
    backgroundColor: isDarkMode ? '#666666' : '#888888',
  },
  lineLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 20,
  },
  lineLabelItem: {
    alignItems: 'center',
  },
  lineLabel: {
    fontSize: 10,
    color: isDarkMode ? '#cccccc' : '#666666',
    fontFamily: 'Courier New',
    textTransform: 'lowercase',
  },
  lineValue: {
    fontSize: 12,
    color: isDarkMode ? '#ffffff' : '#000000',
    fontFamily: 'Courier New',
    marginTop: 2,
  },
  statsContainer: {
    marginHorizontal: 16,
    marginVertical: 20,
    backgroundColor: isDarkMode ? '#111111' : '#f8f8f8',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: isDarkMode ? '#333333' : '#cccccc',
  },
  statItem: {
    fontSize: 14,
    color: isDarkMode ? '#cccccc' : '#666666',
    fontFamily: 'Courier New',
    letterSpacing: 1,
    textTransform: 'lowercase',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
    marginTop: 60,
    marginHorizontal: 24,
  },
  emptyStateText: {
    fontSize: 16,
    color: isDarkMode ? '#888888' : '#666666',
    fontFamily: 'Courier New',
    letterSpacing: 1,
    textTransform: 'lowercase',
    textAlign: 'center',
    fontStyle: 'italic',
  },
});
